---
- hosts: all
  become: yes

  tasks:
    - name: Download Zabbix repository package
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_7.0-2+debian12_all.deb"
        dest: "/tmp/zabbix-release_7.0-2+debian12_all.deb"

    - name: Install Zabbix repository package
      apt:
        deb: "/tmp/zabbix-release_7.0-2+debian12_all.deb"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent to connect to the correct server (passive checks)
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=.*'
        replace: 'Server=192.168.178.90'  # Replace with your Zabbix server IP

    - name: Configure Zabbix agent to connect to the correct server (active checks)
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive=.*'
        replace: 'ServerActive=192.168.178.90'  # Replace with your Zabbix server IP for active checks

    - name: Set the Hostname in the Zabbix agent configuration
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname=.*'
        line: "Hostname={{ inventory_hostname }}"
        state: present

    - name: Start and enable Zabbix agent service
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes
