---
- hosts: all
  become: yes

  tasks:
    - name: Ensure Zabbix repository is installed
      apt:
        deb: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_7.0-2+debian12_all.deb"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=127.0.0.1,192.168.178.165'  # Replace with your Zabbix server IP
        state: present

    - name: Ensure Zabbix agent is started and enabled
      service:
        name: zabbix-agent
        state: started
        enabled: yes
